### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by tomheller**
Improvements to the doc for Usability and SEO value.

There is still stuff to come, I just wanted to open the pull request to get a head start on discussions.

### CODE REVIEW

**Comment by tomheller** [comment]
@katrin-freihofner can you please review the opengraph image. I just quickly put this together as a placeholder, but I'm pretty sure that there are improvements to be made. 
[](https://github.com/Dynatrace/css-groundhog/blob/b1162aec76f7ac3f4d1aa2e4e4d3687a998d1098/assets/images/meta/groundhog-opengraph.png)

**Comment by katrin-freihofner** [comment]
@tomheller I had a look at the [opengraph image](https://github.com/Dynatrace/css-groundhog/blob/b1162aec76f7ac3f4d1aa2e4e4d3687a998d1098/assets/images/meta/groundhog-opengraph.png) and besides that the word groundhog is maybe one pixel smaller than the dynatrace logo - and thats 'i-dipferl-reiterrei' - I think it is great.
:)

**Comment by tomheller** [comment]
referencing #12

**Comment by ddprrt** [comment]
I merge it then

**Pull request merged**
