### PR TITLE
feat(loading spinner): loading spinner examples and basic styling

### PR DESCRIPTION
**Pull request by katrin-freihofner**
This is the first version. 
The next step is to extend this with the following examples:
* Loading spinner in a button
* Loading spinner in an input

### CODE REVIEW

**Comment by katrin-freihofner** [comment]
screen shot 2017-02-08 at 09 02 52
It doesn't work on edge :(

**Comment by tomheller** [comment]
Looks like edge doesn't support svg `stroke-dash-array` and `stroke-dash-offset` animation. 
https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/graphics/svg

**Comment by tomheller** [comment]
Also, this seems on the roadmap, but with medium priority at this point

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/supportcsstransformsonsvg/?q=svg

**Comment by ddprrt** [comment]
@katrin-freihofner I forgot one thing... it's a new feature, can you bump up the minor version number in another PR?

**Comment by tomheller** [comment]
This is awesome. We could see if we could boost performance if we leverage `svg use xlink:href`. Right now CPU is running wild when there are a couple of loading distractors. maybe this can be improved. 

But awesome work @katrin-freihofner

**Pull request merged**
