### PR TITLE
Definition list

### PR DESCRIPTION
**Pull request by katrin-freihofner**
This is not done yet but I definitely need some help.

### CODE REVIEW

**Comment by tomheller** [comment]
Could you attach some screenshots of the current problem, that we know where this stands.

**Comment by katrin-freihofner** [comment]
Sure. 

screen shot 2017-02-02 at 10 00 50
screen shot 2017-02-02 at 10 00 41
screen shot 2017-02-02 at 10 00 27
screen shot 2017-02-02 at 10 00 09

**Comment by katrin-freihofner** [comment]
This is a hack...a bad one.

**Comment by tomheller** [comment]
@ddprrt

**Pull request merged**
